services:
  - type: web
    name: pesapal-callback-listener
    env: docker
    plan: free
    dockerfilePath: ./Dockerfil
    envVars:
      - key: DB_SERVER
        value: 7.tcp.eu.ngrok.io,15590
      - key: DB_NAME
        value: PesapalDB
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: michaelakoko2025
      - key: PORT
        value: 10000
